/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedLocaisRouteImport } from './routes/_authenticated/locais'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedManutencoesIndexRouteImport } from './routes/_authenticated/manutencoes/index'
import { Route as AuthenticatedManutencoesIdRouteImport } from './routes/_authenticated/manutencoes/$id'
import { Route as AuthenticatedManutencoesNovaRouteImport } from './routes/_authenticated/manutencoes/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocaisRoute = AuthenticatedLocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManutencoesIndexRoute =
  AuthenticatedManutencoesIndexRouteImport.update({
    id: '/manutencoes/',
    path: '/manutencoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManutencoesIdRoute =
  AuthenticatedManutencoesIdRouteImport.update({
    id: '/manutencoes/$id',
    path: '/manutencoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManutencoesNovaRoute =
  AuthenticatedManutencoesNovaRouteImport.update({
    id: '/manutencoes/nova',
    path: '/manutencoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/locais': typeof AuthenticatedLocaisRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/manutencoes/$id': typeof AuthenticatedManutencoesIdRoute
  '/manutencoes/nova': typeof AuthenticatedManutencoesNovaRoute
  '/manutencoes/': typeof AuthenticatedManutencoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/locais': typeof AuthenticatedLocaisRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/manutencoes/$id': typeof AuthenticatedManutencoesIdRoute
  '/manutencoes/nova': typeof AuthenticatedManutencoesNovaRoute
  '/manutencoes': typeof AuthenticatedManutencoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/locais': typeof AuthenticatedLocaisRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/manutencoes/$id': typeof AuthenticatedManutencoesIdRoute
  '/_authenticated/manutencoes/nova': typeof AuthenticatedManutencoesNovaRoute
  '/_authenticated/manutencoes/': typeof AuthenticatedManutencoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contratos'
    | '/locais'
    | '/painel'
    | '/servicos'
    | '/manutencoes/$id'
    | '/manutencoes/nova'
    | '/manutencoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contratos'
    | '/locais'
    | '/painel'
    | '/servicos'
    | '/manutencoes/$id'
    | '/manutencoes/nova'
    | '/manutencoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contratos'
    | '/_authenticated/locais'
    | '/_authenticated/painel'
    | '/_authenticated/servicos'
    | '/_authenticated/manutencoes/$id'
    | '/_authenticated/manutencoes/nova'
    | '/_authenticated/manutencoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locais': {
      id: '/_authenticated/locais'
      path: '/locais'
      fullPath: '/locais'
      preLoaderRoute: typeof AuthenticatedLocaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencoes/': {
      id: '/_authenticated/manutencoes/'
      path: '/manutencoes'
      fullPath: '/manutencoes/'
      preLoaderRoute: typeof AuthenticatedManutencoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencoes/$id': {
      id: '/_authenticated/manutencoes/$id'
      path: '/manutencoes/$id'
      fullPath: '/manutencoes/$id'
      preLoaderRoute: typeof AuthenticatedManutencoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencoes/nova': {
      id: '/_authenticated/manutencoes/nova'
      path: '/manutencoes/nova'
      fullPath: '/manutencoes/nova'
      preLoaderRoute: typeof AuthenticatedManutencoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedLocaisRoute: typeof AuthenticatedLocaisRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedManutencoesIdRoute: typeof AuthenticatedManutencoesIdRoute
  AuthenticatedManutencoesNovaRoute: typeof AuthenticatedManutencoesNovaRoute
  AuthenticatedManutencoesIndexRoute: typeof AuthenticatedManutencoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedLocaisRoute: AuthenticatedLocaisRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedManutencoesIdRoute: AuthenticatedManutencoesIdRoute,
  AuthenticatedManutencoesNovaRoute: AuthenticatedManutencoesNovaRoute,
  AuthenticatedManutencoesIndexRoute: AuthenticatedManutencoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
